export {default as Home} from './Home'
export {default as DetailPage} from './DetailPage'
export {default as FavoritePokemon} from './FavoritePokemon'
export {default as Inventory} from './Inventory'
export {default as NotFoundPage} from './NotFoundPage'