export {default as BodyWrapper} from './BodyWrapper'
export {default as Loading} from './Loading'
export {default as PokemonCard} from './PokemonCard'
export {default as PokemonDetails} from './PokemonDetails'
export {default as CreatePokemon} from './CreatePokemon'
export {default as About} from './About'
export {default as NotFound} from './NotFound'